#!/usr/bin/env sh
# . "$(dirname -- "$0")/_/husky.sh"

# npm test

#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# npm test
npx lint-staged

# GitHub Desktop Error fix - use the following line to fix
# git commit -m "message" --no-verify